kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: hello
  name: hello-deployment
  namespace: labs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: docker.io/askcarter/hello:1.0.0
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 80
          - name: health
            containerPort: 81
        args:
        livenessProbe:
          httpGet:
            path: /healthz
            port: 81
            scheme: HTTP
          initialDelaySeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /readiness
            port: 81
            scheme: HTTP
          nitialDelaySeconds: 5
          timeoutSeconds: 1
