kind: Service
apiVersion: v1
metadata:
  labels:
    app: hello
  name: hello-service
  namespace: labs
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
    targetPort: 80
  selector:
    app: hello
